version: '3.4'

services:
  development:
    image: net5-development
    build:
      context: .
      dockerfile: .devcontainer/Debug.Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on: 
      - adventure-works.db
    ports: 
      - 5000:5000
      - 5001:5001
      - 8080:8080

  adventure-works.db:
    image: stvansolano/adventure-works-sql-server:latest
    container_name: adventure-works.db
    environment:
      SA_PASSWORD: "Password.123"
      ACCEPT_EULA: "Y"
    ports: 
      - 1433:1433

  adventure-works-netcore3.api:
    build:
      context: .
      dockerfile: 'samples/webapi/AdventureWorks.Api/Dockerfile'    
    #image: stvansolano/adventure-works-api-netcore3x/1591135993
    ports: 
      - 8081:8080
      - 80:80
    environment: 
      ConnectionStrings_AdventureWorksDatabase: "data source=adventure-works.db;initial catalog=Adventureworks;persist security info=True;user id=sa;password=Password.123;MultipleActiveResultSets=True;App=EntityFramework"
      AdventureWorksDatabase: "data source=adventure-works.db;initial catalog=Adventureworks;persist security info=True;user id=sa;password=Password.123;MultipleActiveResultSets=True;App=EntityFramework"
      
      #ASPNETCORE_URLS: http://+:80;http://*:3000;http://*:8080
      #ASPNETCORE_HTTPS_PORT: 5501
      #ASPNETCORE_Kestrel__Certificates__Default__Password: "@Aa123456"
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    depends_on:
      - adventure-works.db
 