version: '3.4'

services:
  adventure-works.db:
    image: stvansolano/adventure-works-sql-server
    container_name: adventure-works.db
    environment:
      SA_PASSWORD: "Password.123"
      ACCEPT_EULA: "Y"
    ports: 
      - 1433:1433

  adventure-works-netcore3.api:
    image: stvansolano/adventure-works-api-netcore3x:latest
    ports: 
      - 80:80
    environment: 
      ConnectionStrings_AdventureWorksDatabase: "data source=adventure-works.db;initial catalog=Adventureworks;persist security info=True;user id=sa;password=Password.123;MultipleActiveResultSets=True;App=EntityFramework"
      AdventureWorksDatabase: "data source=adventure-works.db;initial catalog=Adventureworks;persist security info=True;user id=sa;password=Password.123;MultipleActiveResultSets=True;App=EntityFramework"
      
      #ASPNETCORE_URLS: http://+:80;http://*:3000;http://*:8080
      #ASPNETCORE_HTTPS_PORT: 5501
      #ASPNETCORE_Kestrel__Certificates__Default__Password: "@Aa123456"
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    depends_on:
      - adventure-works.db
 