version: '3.4'

services:
  development:
    image: net5-development
    build:
      context: .
      dockerfile: .devcontainer/Debug.Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on: 
      - adventure-works.db
    ports: 
      - 5000:5000
      - 5001:5001
      - 8080:8080

  adventure-works.db:
    image: stvansolano/adventure-works-sql-server:latest
    container_name: adventure-works.db
    environment:
      SA_PASSWORD: "Password.123"
      ACCEPT_EULA: "Y"
    ports: 
      - 1433:1433