name: Build and Push Docker Image CI

on:
  push:
    branches:
      - 'master'
    paths:
    - '.github/workflows/master_webapi_docker.yml'
    - 'samples/efcore3x/**'
    - 'samples/webapi/**'

  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login --username stvansolano --password ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        tag=stvansolano/adventure-works-api-netcore3x:$(date +%s)
        docker build . --file samples/webapi/AdventureWorks.Api/Dockerfile --tag $tag
        echo $version
        docker push $tag

    - name: ACR build
      uses: ams0/acr-task-github-action@v1
      with:
        service_principal: ${{ secrets.ACR_SERVICE_PRINCIPAL }}
        service_principal_password: ${{ secrets.ACR_SERVICE_PRINCIPAL_PASSWORD }}
        tenant: ${{ secrets.ACR_TENANT }}
        registry: ${{ secrets.ACR_REGISTRY }}
        repository: ${{ secrets.ACR_REPOSITORY }}
        image: adventure-works-api-net3
        folder: .
        dockerfile: samples/webapi/AdventureWorks.Api/Dockerfile

# c
# az ad sp create-for-rbac --name "myApp" --role contributor --scopes /subscriptions/{SUBSCRIPTION-ID}/resourceGroups/{RESOURCE-GROUP} --sdk-auth
# az role assignment create --assignee <spID> --scope <resourceID of the ACR> --role "Contributor"

# {
#   "clientId": "ID-HERE",
#   "clientSecret": "SECRET-HERE",
#   "tenantId": "TENANT-ID",
#   ...
# }