name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - 'master'
    paths:
    - '.github/workflows/master_webapi_docker.yml'
    - 'samples/efcore3x/**'
    - 'samples/webapi/**'

  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry build & push
      uses: ams0/acr-task-github-action@v1
      with:
        service_principal: ${{ secrets.ACR_SERVICE_PRINCIPAL }}
        service_principal_password: ${{ secrets.ACR_SERVICE_PRINCIPAL_PASSWORD }}
        tenant: ${{ secrets.ACR_TENANT }}
        registry: ${{ secrets.ACR_REGISTRY }}
        repository: ${{ secrets.ACR_REPOSITORY }}
        image: adventure-works-api-net3:latest
        folder: .
        dockerfile: samples/webapi/AdventureWorks.Api/Dockerfile

# az ad sp create-for-rbac --name "myApp" --role contributor --scopes /subscriptions/{SUBSCRIPTION-ID}/resourceGroups/{RESOURCE-GROUP} --sdk-auth
# az role assignment create --assignee <spID> --scope <resourceID of the ACR> --role "Contributor"

# {
#   "clientId": "ID-HERE",
#   "clientSecret": "SECRET-HERE",
#   "tenantId": "TENANT-ID",
#   ...
# }