name: Build and Push Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
    - 'samples/efcore5'
    - 'samples/webapi'

  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login --username stvansolano --password ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        version=$(date +%s)
        docker build . --file samples/webapi/AdventureWorks.Api/Dockerfile --tag adventure-works-api:$version
        echo $version
        docker push stvansolano/adventure-works-api:$version